In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv('adult_with_headers.csv')
df

age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64 
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64 
 11  capital_loss    32561 non-null  int64 
 12  hours_per_week  32561 non-null  int64 
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [4]:
df.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [5]:
df.isnull().sum()
# No null values hence no need to impute!

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

## Scaling data

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
std_scaler=StandardScaler()
mm_scaler=MinMaxScaler()
num_df=df.select_dtypes(include='int')
print("Scaled using standard scaler\n",std_scaler.fit_transform(num_df),'\n')
print('Scaled using min-max scaler\n',mm_scaler.fit_transform(num_df))

Scaled using standard scaler
 [[ 0.03067056 -1.06361075  1.13473876  0.1484529  -0.21665953 -0.03542945]
 [ 0.83710898 -1.008707    1.13473876 -0.14592048 -0.21665953 -2.22215312]
 [-0.04264203  0.2450785  -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 ...
 [ 1.42360965 -0.35877741 -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 [-1.21564337  0.11095988 -0.42005962 -0.14592048 -0.21665953 -1.65522476]
 [ 0.98373415  0.92989258 -0.42005962  1.88842434 -0.21665953 -0.03542945]] 

Scaled using min-max scaler
 [[0.30136986 0.0443019  0.8        0.02174022 0.         0.39795918]
 [0.45205479 0.0482376  0.8        0.         0.         0.12244898]
 [0.28767123 0.13811345 0.53333333 0.         0.         0.39795918]
 ...
 [0.56164384 0.09482688 0.53333333 0.         0.         0.39795918]
 [0.06849315 0.12849934 0.53333333 0.         0.         0.19387755]
 [0.47945205 0.18720338 0.53333333 0.1502415  0.         0.39795918]]


In standard scaler each value is normalized by subtracting it's mean and dividing by standard deviation. It normalize the data disturbution.

Where in min-max scaler it scales its feature to range of '0' to '1', Based on data disturbution we can which one want to use.

## Encoding

In [7]:
cat_df=df.select_dtypes(include='object')
cat_df

workclass    education       marital_status  \
0              State-gov    Bachelors        Never-married   
1       Self-emp-not-inc    Bachelors   Married-civ-spouse   
2                Private      HS-grad             Divorced   
3                Private         11th   Married-civ-spouse   
4                Private    Bachelors   Married-civ-spouse   
...                  ...          ...                  ...   
32556            Private   Assoc-acdm   Married-civ-spouse   
32557            Private      HS-grad   Married-civ-spouse   
32558            Private      HS-grad              Widowed   
32559            Private      HS-grad        Never-married   
32560       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  native_country  \
0            Adm-clerical   Not-in-family   White     Male   United-States   
1         Exec-managerial         Husband   White     Male   United-States   
2       Handlers-cleaners   Not-in-family   White     Male   United-States   
3       Handlers-cleaners         Husband   Black     Male   United-States   
4          Prof-specialty            Wife   Black   Female            Cuba   
...                   ...             ...     ...      ...             ...   
32556        Tech-support            Wife   White   Female   United-States   
32557   Machine-op-inspct         Husband   White     Male   United-States   
32558        Adm-clerical       Unmarried   White   Female   United-States   
32559        Adm-clerical       Own-child   White     Male   United-States   
32560     Exec-managerial            Wife   White   Female   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 9 columns]

In [8]:
len(cat_df['income'].unique())

2

In [17]:
oh=[]
la=[]
for i in cat_df:
    if (len(cat_df[i].unique()))<=5:
        oh.append(i)
    else:
        la.append(i)
print('columns less than 5 categories:',oh)
print('columns greater than 5 categories:',la)        

columns less than 5 categories: ['race', 'sex', 'income']
columns greater than 5 categories: ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'native_country']


In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
one_encoder=OneHotEncoder(sparse_output=False)
lab_encoder=LabelEncoder()
onehot_data=pd.DataFrame(one_encoder.fit_transform(df[oh]),columns=one_encoder.get_feature_names_out(oh))
onehot_data

race_ Amer-Indian-Eskimo  race_ Asian-Pac-Islander  race_ Black  \
0                           0.0                       0.0          0.0   
1                           0.0                       0.0          0.0   
2                           0.0                       0.0          0.0   
3                           0.0                       0.0          1.0   
4                           0.0                       0.0          1.0   
...                         ...                       ...          ...   
32556                       0.0                       0.0          0.0   
32557                       0.0                       0.0          0.0   
32558                       0.0                       0.0          0.0   
32559                       0.0                       0.0          0.0   
32560                       0.0                       0.0          0.0   

       race_ Other  race_ White  sex_ Female  sex_ Male  income_ <=50K  \
0              0.0          1.0          0.0        1.0            1.0   
1              0.0          1.0          0.0        1.0            1.0   
2              0.0          1.0          0.0        1.0            1.0   
3              0.0          0.0          0.0        1.0            1.0   
4              0.0          0.0          1.0        0.0            1.0   
...            ...          ...          ...        ...            ...   
32556          0.0          1.0          1.0        0.0            1.0   
32557          0.0          1.0          0.0        1.0            0.0   
32558          0.0          1.0          1.0        0.0            1.0   
32559          0.0          1.0          0.0        1.0            1.0   
32560          0.0          1.0          1.0        0.0            0.0   

       income_ >50K  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0  
...             ...  
32556           0.0  
32557           1.0  
32558           0.0  
32559           0.0  
32560           1.0  

[32561 rows x 9 columns]

The onehot encoder creates seperate column for every category.It mostly sutable for lesser number of categories.

In [11]:
label_data=pd.DataFrame()
for col in la:
    label_data[col]=lab_encoder.fit_transform(df[col])
label_data    

workclass  education  marital_status  occupation  relationship  \
0              7          9               4           1             1   
1              6          9               2           4             0   
2              4         11               0           6             1   
3              4          1               2           6             0   
4              4          9               2          10             5   
...          ...        ...             ...         ...           ...   
32556          4          7               2          13             5   
32557          4         11               2           7             0   
32558          4         11               6           1             4   
32559          4         11               4           1             3   
32560          5         11               2           4             5   

       native_country  
0                  39  
1                  39  
2                  39  
3                  39  
4                   5  
...               ...  
32556              39  
32557              39  
32558              39  
32559              39  
32560              39  

[32561 rows x 6 columns]

The label encoder gives a label for every category when more of categories are there we use label encoding for those columns. 

Generating new features

As we have age and education number from them we can get work experience for them

In [12]:
df['work_experience']=df['age']-df['education_num']
df

age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  work_experience  
0       <=50K               26  
1       <=50K               37  
2       <=50K               29  
3       <=50K               46  
4       <=50K               15  
...       ...              ...  
32556   <=50K               15  
32557    >50K               31  
32558   <=50K               49  
32559   <=50K               13  
32560    >50K               43  

[32561 rows x 16 columns]

In [13]:
# capital_gain,capital_loss are skewed so that we can apply log transformation to make them normal distributed
df['log_capital_gain'] = np.log1p(df['capital_gain'])
df['log_capital_loss'] = np.log1p(df['capital_loss'])
df

age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  work_experience  log_capital_gain  log_capital_loss  
0       <=50K               26          7.684784               0.0  
1       <=50K               37          0.000000               0.0  
2       <=50K               29          0.000000               0.0  
3       <=50K               46          0.000000               0.0  
4       <=50K               15          0.000000               0.0  
...       ...              ...               ...               ...  
32556   <=50K               15          0.000000               0.0  
32557    >50K               31          0.000000               0.0  
32558   <=50K               49          0.000000               0.0  
32559   <=50K               13          0.000000               0.0  
32560    >50K               43          9.617471               0.0  

[32561 rows x 18 columns]

## Implementing Isolation Forest for Outlier Detection

In [14]:
from sklearn.ensemble import IsolationForest

num_col = df[['age', 'capital_gain', 'capital_loss', 'hours_per_week']]

iso_forest = IsolationForest(contamination=0.01, random_state=42)  
df['outliers'] = iso_forest.fit_predict(num_col)


cleaned_df = df[df['outliers'] == 1]
cleaned_df


age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  work_experience  log_capital_gain  log_capital_loss  outliers  
0       <=50K               26          7.684784               0.0         1  
1       <=50K               37          0.000000               0.0         1  
2       <=50K               29          0.000000               0.0         1  
3       <=50K               46          0.000000               0.0         1  
4       <=50K               15          0.000000               0.0         1  
...       ...              ...               ...               ...       ...  
32556   <=50K               15          0.000000               0.0         1  
32557    >50K               31          0.000000               0.0         1  
32558   <=50K               49          0.000000               0.0         1  
32559   <=50K               13          0.000000               0.0         1  
32560    >50K               43          9.617471               0.0         1  

[32235 rows x 19 columns]

Outliers in the data can make the model to incorrect predictions and also cause it to overfit the models   